### ISSUE TITLE
Missing sequence in plant mt seed DB

### ISSUE THREAD

**Issue by matt-shenton** [Kinggerm/GetOrganelleDB#1]
HI there,

in 0.0.0 and 0.0.1, there is only a single sequence for plant mitochondria, maybe there is an error?

Thanks
MAtt

**Comment by Kinggerm** [comment]
Plant mitogenomes are highly conservative in the coding region and highly variable in the noncoding region. Thus there won't be a big difference between one and a hundred for reads extending/recruitment.

We may build an extensive comprehensive database with limited marginal benefits and set it as optional, but before that, most users would like to use their own seeds.

**Comment by matt-shenton** [comment]
Thanks for the explanation!
Cheers
Matt
