### ISSUE TITLE
Build custom database

### ISSUE THREAD

**Issue by Homap** [Kinggerm/GetOrganelleDB#3]
Hello,

I am working with green algae. I was wondering if I could build my own database containing algal cpDNA and mtDNA genomes to use with GerOrganelle?

Thanks in advance,
Homa

**Comment by smoothyly** [comment]
Is the problem solved?

**Comment by Homap** [comment]
Yes, thank you! I managed to solve it!

**Comment by smoothyly** [comment]
Can you share the method？

Any help would be appreciated！
 
Best wishes,

Zhanwu

**Comment by JianjunJin** [comment]
@smoothyly 
You may like to check
https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-to-assemble-a-target-organelle-genome-using-my-own-reference
https://github.com/Kinggerm/GetOrganelle/wiki/FAQ#how-to-assemble-custom-loci

**Comment by JianjunJin** [comment]
@Homap 
Sorry for the late reply. Being under GetOrganelleDB, this one slipped away from my TODO list.
Glad you solved it.
